### ISSUE TITLE
Error with Pinkie proxy

### ISSUE THREAD

**Issue by herowinb** [Lambda11/let-me-fish#12]
Hi, i'm using pinkie, add defs and opcode but not work.
![image](https://user-images.githubusercontent.com/8396689/52525831-07680780-2ce2-11e9-904a-3b030acf03b8.png)

Error: [dispatch] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.hook (tera-proxy\node_modules\tera-proxy-game\connection\dispatch\index.js:240:27)
    at ModWrapper.hook (tera-proxy\node_modules\tera-proxy-game\connection\dispatch\wrapper.js:199:39)
    at Hook (tera-proxy\mods\let-me-fish-master\index.js:679:18)
    at start (tera-proxy\mods\let-me-fish-master\index.js:464:3)
    at $none (tera-proxy\mods\let-me-fish-master\index.js:87:5)
    at String.subCommandHandler (tera-proxy\mods\command\index.js:182:13)
    at Command.exec (tera-proxy\mods\command\index.js:117:7)
    at handleCommand (tera-proxy\mods\command\index.js:71:15)
    at Object.Command.event [as callback] (tera-proxy\mods\command\index.js:96:22)
    at Dispatch.handle (tera-proxy\node_modules\tera-proxy-game\connection\dispatch\index.js:504:27)

**Comment by Owyn** [comment]
> unmapped packet "S_START_FISHING_MINIGAME"
that says you have no opcodes

**Comment by herowinb** [comment]
Added manual to opcodes, it worked. Sorry, i not read the installation carefully. I think you should put IMG for this step.
![image](https://user-images.githubusercontent.com/8396689/52531324-e507d580-2d45-11e9-8a33-46118013128c.png)
