### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by motuson** [Lambda11/let-me-fish#35]
[19:28:16.791] [command] ERROR: Error: [dispatch] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (C:\Users\Andrey\Desktop\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:233:23)
    at Dispatch.hook (C:\Users\Andrey\Desktop\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:301:21)
    at Module.hook (C:\Users\Andrey\Desktop\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at Hook (C:\Users\Andrey\Desktop\CaaliTeraProxy\mods\let-me-fish-master\index.js:750:18)
    at start (C:\Users\Andrey\Desktop\CaaliTeraProxy\mods\let-me-fish-master\index.js:513:3)
    at $none (C:\Users\Andrey\Desktop\CaaliTeraProxy\mods\let-me-fish-master\index.js:89:5)
    at String.subCommandHandler (C:\Users\Andrey\Desktop\CaaliTeraProxy\mods\command\index.js:263:16)
    at CommandBase.exec (C:\Users\Andrey\Desktop\CaaliTeraProxy\mods\command\index.js:183:16)
    at hookCommand (C:\Users\Andrey\Desktop\CaaliTeraProxy\mods\command\index.js:61:30)
    at Object.CommandBase.mod.hook.event [as callback] (C:\Users\Andrey\Desktop\CaaliTeraProxy\mods\command\index.js:71:29)
    at Dispatch.handle (C:\Users\Andrey\Desktop\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:497:27)
    at Socket.RealClient.socket.on (C:\Users\Andrey\Desktop\CaaliTeraProxy\node_modules\tera-proxy-game\lib\clients\RealClient.js:38:31)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by Owyn** [comment]
try looking at the readme the #installation part :eyes:

**Comment by motuson** [comment]
> попробуйте посмотреть в readme часть #installation 👀

я все првильно раскидал , у меня месяца два назад все работало и я ничего не менял в node modules , но работать перестало

**Comment by Owyn** [comment]
> я ничего не менял

В том то и проблема...

попробуйте посмотреть в readme часть #installation 👀

**Comment by motuson** [comment]
ERROR: Error: [dispatch] hook: unmapped packet means you have no opcodes installed correctly for your current game version. Мне типо самому опкоды для ру искать , я все опкоды правильно раскидал вот прям только что  , которые были в архиве , но ничего не заработало

**Comment by Owyn** [comment]
https://raw.githubusercontent.com/SoliaRdi/auto-fishing/master/protocol.345889.map

Попробуйте

**Comment by motuson** [comment]
теперь все , спасибо
