### ISSUE TITLE
ERROR: Error: [dispatch] hook: unmapped packet "S_START_FISHING_MINIGAME"

### ISSUE THREAD

**Issue by Belial-Lucifer** [Lambda11/let-me-fish#38]
Opcodes are obsolete after v80 patch. No one has made any in the following hours, but just to make sure, I'm reminding everyone in this proxy since I can't imagine living without it. Here's the error code just in case:
`[00:43:08.302] [command] ERROR: Error: [dispatch] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:233:23)
    at Dispatch.hook (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:301:21)
    at Module.hook (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at Hook (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish\index.js:739:18)
    at start (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish\index.js:507:3)
    at $none (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish\index.js:87:5)
    at String.subCommandHandler (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:263:16)
    at CommandBase.exec (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:183:16)
    at hookCommand (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:61:30)
    at Object.CommandBase.mod.hook.event [as callback] (C:\Users\[Username]\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:71:29)`

**Comment by Owyn** [comment]
![55275903-de392000-52fd-11e9-9d8c-73e133e58d29 1](https://user-images.githubusercontent.com/1309656/55873189-a2bd1200-5b97-11e9-9132-2436d832ab0a.png)

**Comment by Belial-Lucifer** [comment]
> 
> 
> ![55275903-de392000-52fd-11e9-9d8c-73e133e58d29 1](https://user-images.githubusercontent.com/1309656/55873189-a2bd1200-5b97-11e9-9132-2436d832ab0a.png)

Did you even read what I wrote correctly ? I know that the opcodes are invalid, that's why I'm getting that error. This is a reminder for opcode update since the game has been updated smh

**Comment by Owyn** [comment]
![55873189-a2bd1200-5b97-11e9-9132-2436d832ab0a](https://user-images.githubusercontent.com/1309656/55893179-72d63480-5bc0-11e9-845b-f6771f85c27d.png)

**Comment by nilsii** [comment]
I had the same problem, I made these opcodes for tera NA and now it works fine... 
what is your region? 
if is NA region, replace this in caaliteraproxy node_modules\tera-data\map\ protocol.345886.map <-( tera na )

S_FISHING_BITE = 27603
S_FISHING_CATCH = 27376
C_END_FISHING_MINIGAME = 46506
C_START_FISHING_MINIGAME = 37509
S_START_FISHING_MINIGAME = 36415
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 44332
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 27482

now it should work well for you

**Comment by Belial-Lucifer** [comment]
Thank you, finally a useful answer. Now it works like a charm.

**Comment by SirBepis** [comment]
Can you update the EU version?Thank you in advance.

**Comment by Lambda11** [comment]
@SirBepis please refer to images above, especially outlined in red text

P.S. it's already updated

**Comment by SirBepis** [comment]
Alright,thank you!

**Comment by giggin** [comment]
I have done everything like it’s written as always but I still can’t use it. I’ve got the same error I posted earlier today. Playing EU

**Comment by SirBepis** [comment]
Same problem as giggin,EU

**Comment by kireallets** [comment]
I need the opcodes from protocol.369074 NA. Do you have?
