### ISSUE TITLE
EU opcodes 

### ISSUE THREAD

**Issue by giggin** [Lambda11/let-me-fish#43]
[19:25:10.434] [command] ERROR: Error: [dispatch] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:233:23)
    at Dispatch.hook (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:301:21)
    at Module.hook (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at Hook (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish-master\index.js:754:18)
    at start (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish-master\index.js:521:3)
    at $none (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish-master\index.js:103:5)
    at String.subCommandHandler (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:263:16)
    at CommandBase.exec (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:183:16)
    at hookCommand (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:61:30)
    at Object.CommandBase.mod.hook.event [as callback] (C:\Users\Mo\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:71:29)

I used Alex packet logger and got told I was trolling and only ru and na got fixed.

**Comment by Owyn** [comment]
All regions after todays maintenance are using same protocol:
"EU": {"version": 344895
, so you'd just have to follow installation instruction from the readme.
there are pictures here https://github.com/Lambda11/let-me-fish/issues/38 if you still need help

**Comment by Okinakuso** [comment]
ive try 3 time but i have the same issue . I play on EU server .

**Comment by Chiiruno** [comment]
I'm also having this problem, even after correctly replacing the OPcodes/defs two times.
I think we may have the wrong def for EU.

**Comment by Owyn** [comment]
OPcodes are literally the same now for all regions, and error `unmapped packet` means you have them installed incorrectly. Try using Caali proxy if you have troubles installing em onto Pinkies one, and vica versa

**Comment by alfonsolaraivan** [comment]
He updated the wrong protocol for EU.
"EU": {"version": 344895
And he updated protocol.345895.map.
Copy and paste the content of protocol.345895.map to protocol.344895.map and it works

**Comment by wtfteddy** [comment]
Got the same Issue.
That what alfonsolaraivan write don´t work.

**Comment by SirBepis** [comment]
Still have the same problem even after replaced and did what alfonsolaraivan said.

**Comment by alfonsolaraivan** [comment]
S_FISHING_BITE = 35300
C_END_FISHING_MINIGAME = 38355
C_START_FISHING_MINIGAME = 25869
S_START_FISHING_MINIGAME = 61667
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46975

puting that on protocol.344895.map worked for me and my friends. (EU)

**Comment by SirBepis** [comment]
What did you do with protocol.345895 @alfonsolaraivan  ?

**Comment by alfonsolaraivan** [comment]
> 
> 
> What did you do with protocol.345895 @alfonsolaraivan ?

Copy pasted the content of opcodes folder to CaaliTeraProxy\node_modules\tera-data\map then edited protocol.344895.map with the content of protocol.345895.map

**Comment by StrayyChildd** [comment]
https://github.com/SoliaRdi/auto-fishing

I dowloaded all 3 protocol files from this one and replaced at map folder - it worked for Let-Me-Fish. Give it a try.

**Comment by SirBepis** [comment]
Why don't I have protocal.345895?

**Comment by alfonsolaraivan** [comment]
> 
> 
> Why don't I have protocal.345895?

https://github.com/Lambda11/let-me-fish/tree/master/opcodes

**Comment by SirBepis** [comment]
I re-downloaded full module..

**Comment by SirBepis** [comment]
I don't know how but I made it work,thanks a lot friend @alfonsolaraivan !

**Comment by Lambda11** [comment]
> Copy and paste the content of protocol.345895.map to protocol.344895.map and it works

just rename the file from 345895 to 344895, fixed now... numbers are hard... mkay?
