### ISSUE TITLE
dismantling fish to craft bait error

### ISSUE THREAD

**Issue by guys101** [Lambda11/let-me-fish#77]
When I was out of bait, the mod tried to dismantle but it says "The item cannot be dismantle" then it says "no fish to dismantle" but I have 12 fishes in the inventory.
https://i.imgur.com/knMssOv

**Comment by Owyn** [comment]
but it said you had 15 fishes, what happened to the other 3? 🤔 

+ you seem to have a LOTS of items in the inventory (132)...

**Comment by Lambda11** [comment]
Try latest version and see what it writes in the chat when problem occurs, added a message when adding fish into dismantler

**Comment by guys101** [comment]
> Try latest version and see what it writes in the chat when problem occurs, added a message when adding fish into dismantler

Nothing happened, it stopped fishing, nothing appeared in that chat either.

**Comment by guys101** [comment]
> but it said you had 15 fishes, what happened to the other 3? 🤔
> 
> * you seem to have a LOTS of items in the inventory (132)...

I tried with fishes only in the inventory, same problem.

**Comment by guys101** [comment]
I tried again, same problem but there are fish dismantling messages https://imgur.com/jACcIIq

**Comment by Owyn** [comment]
do fishes even go into the dismantling window? is it just "dismantle" button which doesn't work does it work if you press it normally with hands?

**Comment by guys101** [comment]
> do fishes even go into the dismantling window? is it just "dismantle" button which doesn't work does it work if you press it normally with hands?

Yes it does worked if I do it manually

**Comment by Owyn** [comment]
Wonder if fish auto - decomposition works for others 🤔 

we'll probably need a log using https://github.com/Owyn/PacketsLogger
from when script tries to decompose fish and for when you manually click decompose and it works to see what's different

**Comment by guys101** [comment]
how do I use that, where do I put the Hexy node module?

**Comment by Owyn** [comment]
![изображение](https://user-images.githubusercontent.com/1309656/63641783-b8515500-c6bc-11e9-9774-4b385d4390d0.png)
Like this, then ingame before getting to the part where script startes putting in fish for dismantling entere these commands: `logBlackClear` , `logC`, `logS`, - it will start logging, then wait for the problem to occur and manually help it dismantle by pressing the button yourself after it got stuck, after that you can turn the logger off with `logs` and `logc` commands again, this will create the tera-log.log file in the root folder 
![изображение](https://user-images.githubusercontent.com/1309656/63641810-09f9df80-c6bd-11e9-9642-a8a261a91842.png)

**Comment by guys101** [comment]
What's wrong here?

[12:29:07.642] [mods] ERROR: Module "hexy.js-master" could not be loaded!
[12:29:07.642] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[12:29:07.643] TypeError: moduleConstructor is not a constructor
    at ModuleManager.load (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:199:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1047:10)

[12:29:07.647] [mods] ERROR: Module "PacketsLogger" (PacketsLogger) could not be loaded!
[12:29:07.648] [mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/
[12:29:07.649] { Error: Cannot find module 'hexy'
Require stack:
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\PacketsLogger-master\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\proxy.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\loader-gui.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\index-gui.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\PacketsLogger-master\index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
  code: 'MODULE_NOT_FOUND',
  requireStack:
   [ 'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\mods\\PacketsLogger-master\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\moduleManager.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\connectionManager.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\proxy.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\loader-gui.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\index-gui.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
     undefined ] }

**Comment by Owyn** [comment]
are you sure you'r putting hexi into node_modules (like on my 1st screenshot) and not into mods folder?

**Comment by Owyn** [comment]
plus `"hexy.js-master` should be without `-master`, like on the screenshot

**Comment by guys101** [comment]
I renamed the folder to hexy.js and put them to both location node_modules and mods folder. Is it the same error?

[12:46:40.894] [mods] ERROR: Module "hexy.js" could not be loaded!
[12:46:40.896] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[12:46:40.897] TypeError: moduleConstructor is not a constructor
    at ModuleManager.load (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:199:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1047:10)

[12:46:40.904] [mods] ERROR: Module "PacketsLogger" (PacketsLogger) could not be loaded!
[12:46:40.905] [mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/
[12:46:40.906] { Error: Cannot find module 'hexy'
Require stack:
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\PacketsLogger-master\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\proxy.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\loader-gui.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\index-gui.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\PacketsLogger-master\index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
  code: 'MODULE_NOT_FOUND',
  requireStack:
   [ 'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\mods\\PacketsLogger-master\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\moduleManager.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\connectionManager.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\proxy.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\loader-gui.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\index-gui.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
     undefined ] }

**Comment by guys101** [comment]
![image](https://user-images.githubusercontent.com/54476482/63642057-bf04ab80-c66d-11e9-9e88-4a24f7fa8956.png)

**Comment by guys101** [comment]
![image](https://user-images.githubusercontent.com/54476482/63642066-130f9000-c66e-11e9-9c1c-fe5e0398155d.png)

**Comment by guys101** [comment]
do you think the problem is the opcodes? I got it from the other auto fishing mod to use with this mod

**Comment by Owyn** [comment]
opcodes should be the same, but defs should be from the right module

you need just one folder `hexy` in modules https://user-images.githubusercontent.com/1309656/63641783-b8515500-c6bc-11e9-9774-4b385d4390d0.png
other folders might give errors

**Comment by guys101** [comment]
Somehow it's still can't find the hexy folder
![image](https://user-images.githubusercontent.com/54476482/63644955-68b55e00-c6a9-11e9-8315-bc962cdb602a.png)

[19:56:16.202] [mods] ERROR: Module "PacketsLogger" (PacketsLogger) could not be loaded!
[19:56:16.204] [mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/
[19:56:16.205] { Error: Cannot find module 'hexy'
Require stack:
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\PacketsLogger-master\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\index.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\proxy.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\loader-gui.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\index-gui.js
- C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\PacketsLogger-master\index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
  code: 'MODULE_NOT_FOUND',
  requireStack:
   [ 'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\mods\\PacketsLogger-master\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\moduleManager.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\index.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\connectionManager.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\proxy.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\loader-gui.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\bin\\index-gui.js',
     'C:\\Users\\Admin\\AppData\\Local\\Programs\\TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
     undefined ] }

**Comment by guys101** [comment]
Now the Let me fish mod has a problem

[20:04:00.929] [mods] ERROR: Module "Let-me-Fish" (let-me-fish) could not be loaded!
[20:04:00.930] [mods] ERROR: Please contact the module's author: https://github.com/Lambda11/let-me-fish/issues
[20:04:00.930] Error: Command already registered:
    at CommandBase.add (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\command\index.js:225:19)
    at CommandBase.add (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\command\index.js:214:22)
    at Command.add (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\command\index.js:366:26)
    at new LetMeFish (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\mods\let-me-fish-master\index.js:98:10)
    at ModuleManager.load (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\Admin\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:199:15)

**Comment by guys101** [comment]
ok it works, I got the log file now, there are players names in it. How do I send you privately?

**Comment by Owyn** [comment]
you can send me it via DM on discord Owyn#1028

**Comment by guys101** [comment]
Sent

**Comment by Owyn** [comment]
as I said
> defs should be from the right module

**Comment by guys101** [comment]
Working perfectly now. Thank you so much.
