### ISSUE TITLE
Getting error when start

### ISSUE THREAD

**Issue by pozso1234** [Lambda11/let-me-fish#88]
I got the following errors, however it is has worked already for few month.
May need update. 
The error message:

[01:56:14.192] [command] ERROR: Error: [dispatch] [let-me-fish] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at Hook (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\mods\let-me-fish-master\index.js:799:18)
    at start (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\mods\let-me-fish-master\index.js:523:3)
    at $none (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\mods\let-me-fish-master\index.js:104:5)
    at String.subCommandHandler (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\mods\command\index.js:281:16)
    at CommandBase.exec (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\dsafg\AppData\Local\Programs\TeraToolbox\mods\command\index.js:88:33)

**Comment by Owyn** [comment]
This error is already explained in the readme https://github.com/Lambda11/let-me-fish#installation

**Comment by pozso1234** [comment]
But what i can do with this, it is not a solution for this issue

**Comment by Tamaou** [comment]
The link is not useless, it has all the instructions on how to get the required opcodes for you region in "Installation and Notes Section". Please Read as it will help you in future where there is an opcode changes for your region.

**Comment by pozso1234** [comment]
I do not understand that instruction. This is chinese for me

**Comment by GrafNikola** [comment]
> Я не понимаю этой инструкции. Это китайский язык для меня
> 
> Не udnerstand как использовать tham потому что нет isntruction для них
> 
> Справка

ask ITunk(Nikolai)#3556
