### ISSUE TITLE
(name: "S_ITEMLIST", code: 57287) is outdated and cannot be used anymore

### ISSUE THREAD

**Issue by mixxedxyz** [Lambda11/let-me-fish#90]
Hi, im tryng to install the script but im getting always the same error. 
someone can help me how i can fix this "outdated" error ? 

```
[11:41:51.550] [command] ERROR: Error: [dispatch] [let-me-fish] hook: Error: version 1 of message (name: "S_ITEMLIST", code: 57287) is outdated and cannot be used anymore
    at Dispatch.createHook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:247:27)
    at Dispatch.hook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at Hook (C:\TeraToolbox\mods\let-me-fish-master\index.js:799:18)
    at start (C:\TeraToolbox\mods\let-me-fish-master\index.js:584:3)
    at $none (C:\TeraToolbox\mods\let-me-fish-master\index.js:104:5)
    at String.subCommandHandler (C:\TeraToolbox\mods\command\index.js:281:16)
    at CommandBase.exec (C:\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\TeraToolbox\mods\command\index.js:81:29)
```

**Comment by Lambda11** [comment]
Updated, now should work, check please

**Comment by mixxedxyz** [comment]
well, i dont know what to say... 
thanks worked! :)
