### ISSUE TITLE
how use module?

### ISSUE THREAD

**Issue by zhenyateraGG** [Lambda11/let-me-fish#92]
scrin
![Безымянный](https://user-images.githubusercontent.com/56781142/68545814-afdeff80-040b-11ea-8339-613977a522ea.png)

**Comment by zhenyateraGG** [comment]
at Dispatch.createHook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at Hook (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:799:18)
    at start (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:523:3)
    at $none (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:104:5)
    at String.subCommandHandler (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:281:16)
    at CommandBase.exec (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:81:29)
[22:17:31.813] [command] ОШИБКА: Error: [dispatch] [let-me-fish] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at Hook (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:799:18)
    at start (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:523:3)
    at $none (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:104:5)
    at String.subCommandHandler (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:281:16)
    at CommandBase.exec (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:81:29)
[22:19:21.256] [command] ОШИБКА: Error: [dispatch] [let-me-fish] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at Hook (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:799:18)
    at start (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:523:3)
    at $none (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:104:5)
    at String.subCommandHandler (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:281:16)
    at CommandBase.exec (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:81:29)
[22:21:33.111] [command] ОШИБКА: Error: [dispatch] [let-me-fish] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at Hook (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:799:18)
    at start (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:523:3)
    at $none (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:104:5)
    at String.subCommandHandler (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:281:16)
    at CommandBase.exec (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:81:29)
[22:33:52.374] [command] ОШИБКА: Error: [dispatch] [let-me-fish] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (W:\проги\TOOLBOX\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at Hook (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:799:18)
    at start (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:523:3)
    at $none (W:\проги\TOOLBOX\TeraToolbox\mods\let-me-fish-master\index.js:104:5)
    at String.subCommandHandler (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:281:16)
    at CommandBase.exec (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (W:\проги\TOOLBOX\TeraToolbox\mods\command\index.js:81:29)

**Comment by Owyn** [comment]
> unmapped packet

https://github.com/Lambda11/let-me-fish#installation

**Comment by zhenyateraGG** [comment]
Thanks!

**Comment by zhenyateraGG** [comment]
There was a problem of auto-craft bait. How to set up auto-craft?

**Comment by Owyn** [comment]
When you first type `fish` there are instructions

**Comment by zhenyateraGG** [comment]
toolbox writes " Your config file is corrupted, bait recipe id is wrong"

**Comment by Owyn** [comment]
have you perhaps edited your config file?

**Comment by zhenyateraGG** [comment]
no

**Comment by zhenyateraGG** [comment]
I don’t even know where he is :)

**Comment by Owyn** [comment]
so, what bait recipe are you using? some new one?

**Comment by zhenyateraGG** [comment]
green medium rice ball

**Comment by Owyn** [comment]
if you mean https://teralore.com/us/item/206001/ you just have to craft one after typing `fish` but before throwing the rod to put it into your config

**Comment by zhenyateraGG** [comment]
Okay I will try

**Comment by zhenyateraGG** [comment]
Thanks, I figured it out
