### ISSUE TITLE
let-me-fish could not be loaded!

### ISSUE THREAD

**Issue by AsunaNiechan** [Lambda11/let-me-fish#98]
[16:31:19.136] [mods] ERROR: Module "Let-me-Fish" (let-me-fish) could not be loaded!
[16:31:19.137] [mods] ERROR: Please contact the module's author: https://github.com/Lambda11/let-me-fish/issues
[16:31:19.138] Error: Command already registered:
    at CommandBase.add (C:\Users\Asuna\AppData\Local\Programs\TeraToolbox\mods\command\index.js:226:19)
    at CommandBase.add (C:\Users\Asuna\AppData\Local\Programs\TeraToolbox\mods\command\index.js:215:22)
    at Command.add (C:\Users\Asuna\AppData\Local\Programs\TeraToolbox\mods\command\index.js:373:19)
    at new LetMeFish (C:\Users\Asuna\AppData\Local\Programs\TeraToolbox\mods\let-me-fish-master\index.js:98:10)
    at ModuleManager.load (C:\Users\Asuna\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\Users\Asuna\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\Asuna\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (C:\Users\Asuna\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:205:15)

**Comment by Owyn** [comment]
> Error: Command already registered:

don't try to run more than one fishing module at once

**Comment by AsunaNiechan** [comment]
okay thx it´s work
